### ISSUE TITLE
Use secure ldap (ldaps) if possible

### ISSUE THREAD

**Issue by edermi** [FatRodzianko/Get-RBCD-Threaded#1]
Your code uses unencrypted ldap if user and password are explicitly specified. You may consider switching to ldaps. There may be also an additional command line switch to disable this behavior if somebody wants clear text credentials on their network.

https://github.com/FatRodzianko/Get-RBCD-Threaded/blob/75129caed4248c5865c852988e09a52302eed28d/Get-RBCD-Threaded/Program.cs#L115

**Comment by FatRodzianko** [comment]
The connection is now hardcoded to use port 636 for the LDAP connection.

Based on my testing the connection would always be done over LDAPS/636 even without specifying the port. Regardless it is now hardcoded. "-i" can be used for an "insecure" connection, but again based on my testing if LDAPS is supported in the environment the connection will use it even when you don't specify port 636.

I tested in a lab with no certificate for LDAPS so that traffic would be sent over plaintext LDAP/389. The creds were sent over NTLM challenge and response so plaintext creds should not be exposed in environments without LDAPS support.

Please correct me if I am mistaken in any of this.
