### ISSUE TITLE
WriteProperty

### ISSUE THREAD

**Issue by 0neAtSec** [FatRodzianko/Get-RBCD-Threaded#2]
Thanks for sharing the tool.
(The account that added the machine to the domain is the account in the MS-DS-CreatorSID property)
The domain account to which the machine is added has an ACL for the machine's WriteProperty, but the tool does not find it.

**Comment by FatRodzianko** [comment]
Hi,

Are you saying that the tool should be checking the MS-DS-CreatorSID property to get the user/identity that added the machine to the domain? I'm hesitant to add checks for who added the system to the domain if it turns out 99% of the time it will just return a user in the domain admins group. I don't want the tool returning Domain Admins since that is useless information to me as a pentester. I'm also lazy and don't want to code out additional checks in the tool to make recursive group membership checks to see if the user returned in MS-DS-CreatorSID is a member of a group that's a member of a group that's a member of Domain Admins and so on.

For the WriteProp check, the tool only checks if a user/group/computer/whatever has WriteProp to the ms-DS-Allowed-To-Act-On-Behalf-Of-Other-Identity AD property. What property does your domain account have WriteProp privileges too?

**Comment by 0neAtSec** [comment]
Hi,

By default the following accounts have permission to modify machine account msDS - AllowedToActOnBehalfOfOtherIdentity attributes:
1.Domain admins
2.mS-DS-CreatorSID
3.NT AUTHORITY\SELF

mS-DS-CreatorSID is available only on machines that are added to a domain using a non-domain administrator account.
A company may have a special account for adding domains. Although this account usually only has normal domain user rights, if we control this account, we can take down a large number of machines. It's also a way to move horizontally.

**Comment by FatRodzianko** [comment]
Ok. Thanks for letting me know. I'll see if I can figure out how to add that check and test it out

**Comment by 0neAtSec** [comment]
Reference code from [https://blog.ateam.qianxin.com/](https://blog.ateam.qianxin.com/post/wei-ruan-bu-ren-de-0day-zhi-yu-nei-ben-di-ti-quan-lan-fan-qie/#新的攻击面-ms-ds-creatorsid)
```
using System;
using System.Security.Principal;
using System.DirectoryServices;

namespace ConsoleApp9
{
    class Program
    {

        static void Main(string[] args)
        {

            DirectoryEntry ldap_conn = new DirectoryEntry("LDAP://dc=redteam,dc=com");

            DirectorySearcher search = new DirectorySearcher(ldap_conn);

            String query = "(&(objectClass=computer))";//查找计算机

            search.Filter = query;

            foreach (SearchResult r in search.FindAll())
            {
                String mS_DS_CreatorSID="";
                String computername = "";
                try
                {
                    computername = r.Properties["dNSHostName"][0].ToString();
                    
                    mS_DS_CreatorSID = (new SecurityIdentifier((byte[])r.Properties["mS-DS-CreatorSID"][0], 0)).ToString();
                    //Console.WriteLine("{0} {1}\n", computername, mS_DS_CreatorSID);
                }
                catch
                {
                    ;
                }
                //再通过sid找用户名
                String UserQuery = "(&(objectClass=user))";
                DirectorySearcher search2 = new DirectorySearcher(ldap_conn);
                search2.Filter = UserQuery;
                
                foreach (SearchResult u in search2.FindAll())
                {
                    String user_sid = (new SecurityIdentifier((byte[])u.Properties["objectSid"][0], 0)).ToString();
                    
                    
                    if (user_sid == mS_DS_CreatorSID) {
                        //Console.WriteLine("debug");
                        String username = u.Properties["name"][0].ToString();
                        Console.WriteLine("[*] [{0}] -> creator  [{1}]",computername, username);
                    }
                }  
            }
        }
    }
}
```
![图片](https://user-images.githubusercontent.com/43740972/129652275-0f4bec17-7f62-4f7e-85ba-45a7632e4f93.png)
